// database/seeding/items/materials/skinning/insertApprenticeSkins.js
// This script inserts Apprentice-level skinning produce into the 'profession_materials' table.

import db from '../../../../connection.js'; // Correct path to connection.js

export default async function seedNoviceSkins() {
    console.log('Seeding Novice Skinning');

    const skins = [
        { name: 'Boar Leather', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Boar', 
            weight: 1, 
            armor_flat_bonus: 12, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 4, 
            aura_value_bonus: 4,  
        },

        { name: 'Deer Leather', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Deer',  
            weight: 1, 
            armor_flat_bonus: 12, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 4, 
            aura_value_bonus: 4, 
        },

        { name: 'Elk Leather', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Elk', 
            weight: 1, 
            armor_flat_bonus: 12, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 4, 
            aura_value_bonus: 4, 
        },

        { name: 'Ox Leather', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Ox', 
            weight: 1, 
            armor_flat_bonus: 12, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 4, 
            aura_value_bonus: 4,
        },

        { name: 'Basilisk Scales', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Basilisk', 
            weight: 2, 
            armor_flat_bonus: 24, 
            physical_resistance_bonus: 2, 
            magic_resistance_bonus: 4, 
            dodge_chance_bonus: 2, 
            aura_value_bonus: 2,
        },

        { name: 'Blue Dragon Scales', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Dragon', 
            weight: 2, 
            armor_flat_bonus: 24, 
            physical_resistance_bonus: 2, 
            magic_resistance_bonus: 4, 
            dodge_chance_bonus: 2, 
            aura_value_bonus: 4,
        },

        { name: 'Black Dragon Scales', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Dragon', 
            weight: 2, 
            armor_flat_bonus: 24,  
            physical_resistance_bonus: 3, 
            magic_resistance_bonus: 4, 
            dodge_chance_bonus: 2, 
            aura_value_bonus: 2,
        },

        { name: 'Green Dragon Scales', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Dragon', 
            weight: 2, 
            armor_flat_bonus: 24, 
            physical_resistance_bonus: 2, 
            magic_resistance_bonus: 4, 
            dodge_chance_bonus: 3, 
            aura_value_bonus: 2,
        },

        { name: 'Red Dragon Scales', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Dragon', 
            weight: 2, 
            armor_flat_bonus: 24, 
            physical_resistance_bonus: 2, 
            magic_resistance_bonus: 5, 
            dodge_chance_bonus: 2, 
            aura_value_bonus: 2,
        },

        { name: 'White Dragon Scales', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Dragon', 
            weight: 2, 
            armor_flat_bonus: 24, 
            physical_resistance_bonus: 2, 
            magic_resistance_bonus: 4, 
            dodge_chance_bonus: 2.5, 
            aura_value_bonus: 2.5,
        },

        { name: 'Wyvern Scales', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Dragon', 
            weight: 2, 
            armor_flat_bonus: 18, 
            physical_resistance_bonus: 2, 
            magic_resistance_bonus: 2, 
            dodge_chance_bonus: 3, 
            aura_value_bonus: 3,
        },
        
        { name: 'Bear Fur', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Bear', 
            weight: 1, 
            armor_flat_bonus: 18, 
            physical_resistance_bonus: 2, 
            magic_resistance_bonus: 2, 
            dodge_chance_bonus: 2, 
            aura_value_bonus: 2,
        },

        { name: 'Wolf Fur', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Wolf', 
            weight: 1, 
            armor_flat_bonus: 14, 
            physical_resistance_bonus: 1.5, 
            magic_resistance_bonus: 2, 
            dodge_chance_bonus: 3, 
            aura_value_bonus: 3,
        },

        { name: 'Panther Fur', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Panther', 
            weight: 1, 
            armor_flat_bonus: 10, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 5, 
            aura_value_bonus: 4,
        },

        { name: 'Lynx Fur', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Lynx', 
            weight: 1, 
            armor_flat_bonus: 8, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 5, 
            aura_value_bonus: 4,
        },

        { name: 'Tiger Fur', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Tiger', 
            weight: 1, 
            armor_flat_bonus: 12, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 4, 
            aura_value_bonus: 4,
        },

        { name: 'Lion Fur', 
            rarity: 'Novice', 
            type: 'Skinnings', 
            subtype: 'Lion', 
            weight: 1, 
            armor_flat_bonus: 12, 
            physical_resistance_bonus: 1, 
            magic_resistance_bonus: 1, 
            dodge_chance_bonus: 4, 
            aura_value_bonus: 4,
        },
    ];

    try {
        for (const skin of skins) {
            await db.run(
                `INSERT OR IGNORE INTO profession_materials (
                    name, description, rarity, type, subtype, weight,
                    strength_bonus, stamina_bonus, endurance_bonus, conditioning_bonus,
                    agility_bonus, dexterity_bonus, celerity_bonus, grace_bonus,
                    intelligence_bonus, acuity_bonus, alacrity_bonus, clarity_bonus,
                    essence_bonus, spirit_bonus, aura_bonus, toughness_bonus,
                    strength_percent_bonus, agility_percent_bonus, intelligence_percent_bonus,
                    armor_flat_bonus, armor_percent_bonus, magic_resistance_bonus,
                    physical_resistance_bonus, dps_bonus, dps_percent_bonus,
                    attack_speed_bonus, attack_speed_percent_bonus, crit_chance_bonus,
                    crit_damage_bonus, block_chance_bonus, block_value_bonus, dodge_chance_bonus,
                    parry_chance_bonus, parry_value_bonus, deflection_chance_bonus,
                    deflection_value_bonus, aura_value_bonus,
                    active_effect_text, lore_text
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);`,
                [
                    skin.name, skin.description, skin.rarity, skin.type, skin.subtype, skin.weight, 
                    skin.strength_bonus || 0, skin.stamina_bonus || 0, skin.endurance_bonus || 0, skin.conditioning_bonus || 0,
                    skin.agility_bonus || 0, skin.dexterity_bonus || 0, skin.celerity_bonus || 0, skin.grace_bonus || 0,
                    skin.intelligence_bonus || 0, skin.acuity_bonus || 0, skin.alacrity_bonus || 0, skin.clarity_bonus || 0,
                    skin.essence_bonus || 0, skin.spirit_bonus || 0, skin.aura_bonus || 0, skin.toughness_bonus || 0,
                    skin.strength_percent_bonus || 0.0, skin.agility_percent_bonus || 0.0, skin.intelligence_percent_bonus || 0.0,
                    skin.armor_flat_bonus || 0, skin.armor_percent_bonus || 0.0, skin.magic_resistance_bonus || 0,
                    skin.physical_resistance_bonus || 0, skin.dps_bonus || 0.0, skin.dps_percent_bonus || 0.0,
                    skin.attack_speed_bonus || 0.0, skin.attack_speed_percent_bonus || 0.0, skin.crit_chance_bonus || 0.0,
                    skin.crit_damage_bonus || 0.0, skin.block_chance_bonus || 0.0, skin.block_value_bonus || 0,
                    skin.dodge_chance_bonus || 0.0, skin.parry_chance_bonus || 0.0, skin.parry_value_bonus || 0,
                    skin.deflection_chance_bonus || 0.0, skin.deflection_value_bonus || 0, skin.aura_value_bonus || 0,
                    skin.active_effect_text || null, skin.lore_text || null
                ]
            );
        }
        console.log('Success'); // Updated console log
    } catch (err) {
        console.error('Error: ', err.message); // Updated console log
        throw err;
    }
}
